# Generated by Django 2.2.4 on 2019-08-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_summary',
            field=models.TextField(default='this is cool'),
        ),
    ]
